language: go
sudo: false
install: true

matrix:
  include:
    - os: linux
      go: "1.12.x"
      sudo: true
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

    - os: osx
      go: "1.12.x"
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $HOME/gopath/pkg/mod

before_install:
  - env GO111MODULE=off go get -u golang.org/x/lint/golint
  - env GO111MODULE=off make bundle-install

before_script:
  - mkdir $HOME/.kube
  - curl https://raw.githubusercontent.com/projectcalico/cni-plugin/master/kubeconfig.sample > $HOME/.kube/config

script:
  - env GO111MODULE=on make ci
