---
Source: "master-0.example.com" # can also point to directory
SSHCreds:
  Login: "root"
  PrivateKey: "/home/example/.ssh/key"
  Port: 22
InsecureHostKey: true
ClusterName: "example-cluster.examle.com"
OutputDir: "./data"
# MasterConfigFile and NodeConfigFile are optional fields
# Use only if cluster was configured with different config locations
MasterConfigFile: "/etc/origin/master/master-config.yaml"
NodeConfigFile: "/etc/origin/node/node-config.yaml"
